kind: Service
apiVersion: v1
metadata:
    name: my-service
spec:
  selector:
        app: hello-world
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort:9376
  externalIPs:
  - 192.168.1.5
